package me.ronygomes.ums.api.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import java.io.Serial;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

@Entity
@Table(name = "students")
public class Student extends AbstractEntity {

    private static final String REGISTRATION_NUMBER_REGEX_PATTERN = "^\\d{4}-[A-Z]{1,10}-\\d{4}$";

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @SequenceGenerator(name = "students_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "students_seq")
    private Long id;

    @NotNull
    @Size(min = 1, max = 200)
    @Column(nullable = false, length = 200)
    private String fullName;

    @NotNull
    @Size(min = 5, max = 100)
    @Pattern(regexp = EMAIL_REGEX_PATTERN, message = "invalid email format")
    @Column(nullable = false, unique = true, length = 100)
    private String email;

    @Size(max = 14)
    @Pattern(regexp = PHONE_REGEX_PATTERN, message = "invalid contact number format")
    @Column(length = 14)
    private String contactNumber;

    @Size(max = 1000)
    @Column(length = 1000)
    private String address;

    @ManyToOne
    @JsonIgnore
    @JoinColumn(name = "department_id", nullable = false, foreignKey = @ForeignKey(name = "fk_students_department_id"))
    private Department department;

    @NotNull
    @PastOrPresent
    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Date registrationDate;

    @NotNull
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    // Autogenerated <4d-Year>-<Dept-Code>-<4d-Unique>
    @Pattern(regexp = REGISTRATION_NUMBER_REGEX_PATTERN, message = "invalid registration number")
    @Column(nullable = false, updatable = false, unique = true, length = 20)
    private String registrationNumber;

    @Valid
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderColumn(name = "idx")
    @JoinColumn(name = "student_id", nullable = false, foreignKey = @ForeignKey(name = "fk_student_educations_student_id"))
    private List<Education> educations;

    @Transient
    private String departmentCode;

    public Student() {
        this.educations = new ArrayList<>();
    }

    @Override
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getRegistrationNumber() {
        return registrationNumber;
    }

    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    public List<Education> getEducations() {
        return educations;
    }

    public void setEducations(List<Education> educations) {
        this.educations = educations;
    }

    public String getDepartmentCode() {
        return Objects.nonNull(departmentCode) ? departmentCode
                : Objects.nonNull(department) ? department.getCode() : null;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    public void merge(Student ps) {
        if (Objects.nonNull(ps.getFullName())) {
            setFullName(ps.getFullName());
        }

        if (Objects.nonNull(ps.getEmail())) {
            setEmail(ps.getEmail());
        }

        if (Objects.nonNull(ps.getContactNumber())) {
            setContactNumber(ps.getContactNumber());
        }

        if (Objects.nonNull(ps.getAddress())) {
            setAddress(ps.getAddress());
        }

        if (Objects.nonNull(ps.getRegistrationDate())) {
            setRegistrationDate(ps.getRegistrationDate());
        }

        if (Objects.nonNull(ps.getRegistrationNumber())) {
            setRegistrationNumber(ps.getRegistrationNumber());
        }

        if (Objects.nonNull(ps.getDepartmentCode())) {
            setDepartmentCode(ps.getDepartmentCode());
        }

        if (Objects.nonNull(ps.getEducations()) && !ps.getEducations().isEmpty()) {
            setEducations(ps.getEducations());
        }
    }

    public int findEducationById(long educationId) {
        for (int i = 0; i < getEducations().size(); i++) {
            if (educationId == getEducations().get(i).getId()) {
                return i;
            }
        }

        return -1;
    }
}