-- Seed data for the University Management System.
-- Loaded by Postgres AFTER init.sql (docker-entrypoint-initdb.d runs files
-- alphabetically: init.sql -> seed.sql). Departments and teacher_designations
-- come from init.sql and are referenced here by their natural keys.

-- 30 teachers spanning every department and all four designations.
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Anisul Karim', 'House 1, Road 2, Dhaka', 'anisul.karim@ums.edu', '+8801700000001', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'CSE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Farhana Rahman', 'House 2, Road 3, Dhaka', 'farhana.rahman@ums.edu', '+8801700000002', 9.0, (SELECT id FROM teacher_designations WHERE title = 'Associate Professor'), (SELECT id FROM departments WHERE code = 'CSE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Sabbir Ahmed', 'House 3, Road 4, Dhaka', 'sabbir.ahmed@ums.edu', '+8801700000003', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'CSE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Nusrat Jahan', 'House 4, Road 5, Dhaka', 'nusrat.jahan@ums.edu', '+8801700000004', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'CSE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Tanvir Hasan', 'House 5, Road 6, Dhaka', 'tanvir.hasan@ums.edu', '+8801700000005', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'CSE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Mehnaz Chowdhury', 'House 6, Road 7, Dhaka', 'mehnaz.chowdhury@ums.edu', '+8801700000006', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'CSE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Kamrul Islam', 'House 7, Road 8, Dhaka', 'kamrul.islam@ums.edu', '+8801700000007', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'EEE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Shahida Akter', 'House 8, Road 9, Dhaka', 'shahida.akter@ums.edu', '+8801700000008', 9.0, (SELECT id FROM teacher_designations WHERE title = 'Associate Professor'), (SELECT id FROM departments WHERE code = 'EEE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Rashedul Alam', 'House 9, Road 10, Dhaka', 'rashedul.alam@ums.edu', '+8801700000009', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'EEE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Sadia Noor', 'House 10, Road 11, Dhaka', 'sadia.noor@ums.edu', '+8801700000010', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'EEE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Imran Hossain', 'House 11, Road 12, Dhaka', 'imran.hossain@ums.edu', '+8801700000011', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'EEE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Golam Mostafa', 'House 12, Road 1, Dhaka', 'golam.mostafa@ums.edu', '+8801700000012', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'CE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Rafiqul Bari', 'House 13, Road 2, Dhaka', 'rafiqul.bari@ums.edu', '+8801700000013', 9.0, (SELECT id FROM teacher_designations WHERE title = 'Associate Professor'), (SELECT id FROM departments WHERE code = 'CE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Mahfuza Sultana', 'House 14, Road 3, Dhaka', 'mahfuza.sultana@ums.edu', '+8801700000014', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'CE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Arif Mahmud', 'House 15, Road 4, Dhaka', 'arif.mahmud@ums.edu', '+8801700000015', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'CE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Nazrul Huq', 'House 16, Road 5, Dhaka', 'nazrul.huq@ums.edu', '+8801700000016', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'MPE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Selina Parvin', 'House 17, Road 6, Dhaka', 'selina.parvin@ums.edu', '+8801700000017', 9.0, (SELECT id FROM teacher_designations WHERE title = 'Associate Professor'), (SELECT id FROM departments WHERE code = 'MPE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Zahidul Islam', 'House 18, Road 7, Dhaka', 'zahidul.islam@ums.edu', '+8801700000018', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'MPE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Rakibul Hasan', 'House 19, Road 8, Dhaka', 'rakibul.hasan@ums.edu', '+8801700000019', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'MPE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Momtaz Begum', 'House 20, Road 9, Dhaka', 'momtaz.begum@ums.edu', '+8801700000020', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'TE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Habibur Rahman', 'House 21, Road 10, Dhaka', 'habibur.rahman@ums.edu', '+8801700000021', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'TE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Shabnam Ferdous', 'House 22, Road 11, Dhaka', 'shabnam.ferdous@ums.edu', '+8801700000022', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'TE'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Aminul Haque', 'House 23, Road 12, Dhaka', 'aminul.haque@ums.edu', '+8801700000023', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'A&S'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Ruma Das', 'House 24, Road 1, Dhaka', 'ruma.das@ums.edu', '+8801700000024', 9.0, (SELECT id FROM teacher_designations WHERE title = 'Associate Professor'), (SELECT id FROM departments WHERE code = 'A&S'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Jamil Uddin', 'House 25, Road 2, Dhaka', 'jamil.uddin@ums.edu', '+8801700000025', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'A&S'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Shamima Nasrin', 'House 26, Road 3, Dhaka', 'shamima.nasrin@ums.edu', '+8801700000026', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'ARCH'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Tahmid Zaman', 'House 27, Road 4, Dhaka', 'tahmid.zaman@ums.edu', '+8801700000027', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'ARCH'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Farzana Kabir', 'House 28, Road 5, Dhaka', 'farzana.kabir@ums.edu', '+8801700000028', 15.0, (SELECT id FROM teacher_designations WHERE title = 'Lecturer'), (SELECT id FROM departments WHERE code = 'ARCH'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Dr. Mizanur Rahman', 'House 29, Road 6, Dhaka', 'mizanur.rahman@ums.edu', '+8801700000029', 6.0, (SELECT id FROM teacher_designations WHERE title = 'Professor'), (SELECT id FROM departments WHERE code = 'SoB'), gen_random_uuid(), 0);
INSERT INTO teachers VALUES(NEXTVAL('teachers_seq'), 'Nabila Haque', 'House 30, Road 7, Dhaka', 'nabila.haque@ums.edu', '+8801700000030', 12.0, (SELECT id FROM teacher_designations WHERE title = 'Assistant Professor'), (SELECT id FROM departments WHERE code = 'SoB'), gen_random_uuid(), 0);

-- 100+ courses distributed across departments and semesters.
-- CSE
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-1101', 'Introduction to Programming', 3.0, 'Introduction to Programming course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-1102', 'Discrete Mathematics', 3.0, 'Discrete Mathematics course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-1201', 'Data Structures', 4.0, 'Data Structures course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-1202', 'Digital Logic Design', 2.0, 'Digital Logic Design course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-2101', 'Object Oriented Programming', 3.0, 'Object Oriented Programming course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-2102', 'Design and Analysis of Algorithms', 3.0, 'Design and Analysis of Algorithms course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-2201', 'Database Management Systems', 4.0, 'Database Management Systems course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-2202', 'Computer Architecture', 2.0, 'Computer Architecture course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-3101', 'Operating Systems', 3.0, 'Operating Systems course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-3102', 'Computer Networks', 3.0, 'Computer Networks course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-3201', 'Software Engineering', 4.0, 'Software Engineering course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-3202', 'Theory of Computation', 2.0, 'Theory of Computation course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-4101', 'Artificial Intelligence', 3.0, 'Artificial Intelligence course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-4102', 'Machine Learning', 3.0, 'Machine Learning course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-4201', 'Compiler Design', 4.0, 'Compiler Design course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CSE-4202', 'Distributed Systems', 2.0, 'Distributed Systems course offered by the CSE department.', (SELECT id FROM departments WHERE code = 'CSE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- EEE
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-1101', 'Electrical Circuits I', 3.0, 'Electrical Circuits I course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-1201', 'Electrical Circuits II', 3.0, 'Electrical Circuits II course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-2101', 'Electronic Devices', 4.0, 'Electronic Devices course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-2102', 'Signals and Systems', 2.0, 'Signals and Systems course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-2201', 'Electromagnetic Fields', 3.0, 'Electromagnetic Fields course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-2202', 'Analog Electronics', 3.0, 'Analog Electronics course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-3101', 'Digital Electronics', 4.0, 'Digital Electronics course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-3102', 'Power Systems I', 2.0, 'Power Systems I course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-3201', 'Control Systems', 3.0, 'Control Systems course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-3202', 'Microprocessors and Interfacing', 3.0, 'Microprocessors and Interfacing course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-4101', 'Communication Engineering', 4.0, 'Communication Engineering course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-4102', 'Power Electronics', 2.0, 'Power Electronics course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-4201', 'VLSI Design', 3.0, 'VLSI Design course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'EEE-4202', 'Electrical Machines', 3.0, 'Electrical Machines course offered by the EEE department.', (SELECT id FROM departments WHERE code = 'EEE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- CE
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-1101', 'Engineering Mechanics', 4.0, 'Engineering Mechanics course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-1102', 'Engineering Drawing', 2.0, 'Engineering Drawing course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-1201', 'Surveying', 3.0, 'Surveying course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-1202', 'Fluid Mechanics', 3.0, 'Fluid Mechanics course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-2101', 'Strength of Materials', 4.0, 'Strength of Materials course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-2102', 'Structural Analysis I', 2.0, 'Structural Analysis I course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-2201', 'Structural Analysis II', 3.0, 'Structural Analysis II course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-2202', 'Geotechnical Engineering I', 3.0, 'Geotechnical Engineering I course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-3101', 'Reinforced Concrete Design', 4.0, 'Reinforced Concrete Design course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-3102', 'Transportation Engineering', 2.0, 'Transportation Engineering course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-3201', 'Environmental Engineering', 3.0, 'Environmental Engineering course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-3202', 'Hydrology and Water Resources', 3.0, 'Hydrology and Water Resources course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-4101', 'Steel Structures Design', 4.0, 'Steel Structures Design course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'CE-4201', 'Construction Management', 2.0, 'Construction Management course offered by the CE department.', (SELECT id FROM departments WHERE code = 'CE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- MPE
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-1101', 'Engineering Thermodynamics', 3.0, 'Engineering Thermodynamics course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-1201', 'Manufacturing Processes', 3.0, 'Manufacturing Processes course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-2101', 'Mechanics of Machines', 4.0, 'Mechanics of Machines course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-2102', 'Fluid Mechanics and Machinery', 2.0, 'Fluid Mechanics and Machinery course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-2201', 'Heat and Mass Transfer', 3.0, 'Heat and Mass Transfer course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-2202', 'Machine Design I', 3.0, 'Machine Design I course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-3101', 'Machine Design II', 4.0, 'Machine Design II course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-3102', 'Industrial Engineering', 2.0, 'Industrial Engineering course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-3201', 'Internal Combustion Engines', 3.0, 'Internal Combustion Engines course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-3202', 'Refrigeration and Air Conditioning', 3.0, 'Refrigeration and Air Conditioning course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-4101', 'Production Planning and Control', 4.0, 'Production Planning and Control course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-4102', 'Robotics and Automation', 2.0, 'Robotics and Automation course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'MPE-4201', 'Mechatronics', 3.0, 'Mechatronics course offered by the MPE department.', (SELECT id FROM departments WHERE code = 'MPE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- TE
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-1101', 'Textile Raw Materials', 3.0, 'Textile Raw Materials course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-1201', 'Yarn Manufacturing I', 4.0, 'Yarn Manufacturing I course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-2101', 'Yarn Manufacturing II', 2.0, 'Yarn Manufacturing II course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-2102', 'Fabric Manufacturing I', 3.0, 'Fabric Manufacturing I course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-2201', 'Fabric Manufacturing II', 3.0, 'Fabric Manufacturing II course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-3101', 'Wet Processing I', 4.0, 'Wet Processing I course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-3201', 'Wet Processing II', 2.0, 'Wet Processing II course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-3202', 'Textile Testing and Quality Control', 3.0, 'Textile Testing and Quality Control course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-4101', 'Apparel Manufacturing', 3.0, 'Apparel Manufacturing course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-4102', 'Textile Coloration', 4.0, 'Textile Coloration course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'TE-4201', 'Technical Textiles', 2.0, 'Technical Textiles course offered by the TE department.', (SELECT id FROM departments WHERE code = 'TE'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- A&S
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1101', 'Calculus I', 3.0, 'Calculus I course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1102', 'Physics I', 3.0, 'Physics I course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1103', 'Chemistry', 4.0, 'Chemistry course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1104', 'English Composition', 2.0, 'English Composition course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1201', 'Calculus II', 3.0, 'Calculus II course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1202', 'Physics II', 3.0, 'Physics II course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-1203', 'Linear Algebra', 4.0, 'Linear Algebra course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-2101', 'Differential Equations', 2.0, 'Differential Equations course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-2102', 'Probability and Statistics', 3.0, 'Probability and Statistics course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-2201', 'Complex Variables', 3.0, 'Complex Variables course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-3101', 'Engineering Ethics', 4.0, 'Engineering Ethics course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'A&S-3201', 'Technical Writing', 2.0, 'Technical Writing course offered by the A&S department.', (SELECT id FROM departments WHERE code = 'A&S'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);

-- ARCH
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-1101', 'Architectural Design I', 3.0, 'Architectural Design I course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-1102', 'History of Architecture', 3.0, 'History of Architecture course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-1201', 'Architectural Design II', 4.0, 'Architectural Design II course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-1202', 'Building Materials and Construction', 2.0, 'Building Materials and Construction course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-2101', 'Architectural Design III', 3.0, 'Architectural Design III course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-2102', 'Environmental Design', 3.0, 'Environmental Design course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-2201', 'Urban Design and Planning', 4.0, 'Urban Design and Planning course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-3101', 'Structural Systems in Architecture', 2.0, 'Structural Systems in Architecture course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-3201', 'Landscape Architecture', 3.0, 'Landscape Architecture course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-4101', 'Interior Architecture', 3.0, 'Interior Architecture course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'FOURTH_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'ARCH-4201', 'Sustainable Architecture', 4.0, 'Sustainable Architecture course offered by the ARCH department.', (SELECT id FROM departments WHERE code = 'ARCH'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- SoB
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-1101', 'Principles of Management', 2.0, 'Principles of Management course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-1102', 'Financial Accounting', 3.0, 'Financial Accounting course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'FIRST_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-1201', 'Microeconomics', 3.0, 'Microeconomics course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-1202', 'Business Communication', 4.0, 'Business Communication course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'FIRST_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-2101', 'Macroeconomics', 2.0, 'Macroeconomics course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-2102', 'Marketing Management', 3.0, 'Marketing Management course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'SECOND_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-2201', 'Organizational Behavior', 3.0, 'Organizational Behavior course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'SECOND_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-3101', 'Business Finance', 4.0, 'Business Finance course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-3102', 'Operations Management', 2.0, 'Operations Management course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'THIRD_YEAR_FIRST', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-3201', 'Human Resource Management', 3.0, 'Human Resource Management course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'THIRD_YEAR_SECOND', gen_random_uuid(), 0);
INSERT INTO courses VALUES(NEXTVAL('courses_seq'), 'SoB-4201', 'Strategic Management', 3.0, 'Strategic Management course offered by the SoB department.', (SELECT id FROM departments WHERE code = 'SoB'), 'FOURTH_YEAR_SECOND', gen_random_uuid(), 0);

-- Course <-> Teacher assignments (a course may have multiple instructors).
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-1101'), (SELECT id FROM teachers WHERE email = 'anisul.karim@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-1101'), (SELECT id FROM teachers WHERE email = 'farhana.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-1102'), (SELECT id FROM teachers WHERE email = 'farhana.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-1201'), (SELECT id FROM teachers WHERE email = 'sabbir.ahmed@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-1202'), (SELECT id FROM teachers WHERE email = 'nusrat.jahan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-1202'), (SELECT id FROM teachers WHERE email = 'tanvir.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-2101'), (SELECT id FROM teachers WHERE email = 'tanvir.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-2102'), (SELECT id FROM teachers WHERE email = 'mehnaz.chowdhury@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-2201'), (SELECT id FROM teachers WHERE email = 'anisul.karim@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-2201'), (SELECT id FROM teachers WHERE email = 'farhana.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-2202'), (SELECT id FROM teachers WHERE email = 'farhana.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-3101'), (SELECT id FROM teachers WHERE email = 'sabbir.ahmed@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-3102'), (SELECT id FROM teachers WHERE email = 'nusrat.jahan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-3102'), (SELECT id FROM teachers WHERE email = 'tanvir.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-3201'), (SELECT id FROM teachers WHERE email = 'tanvir.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-3202'), (SELECT id FROM teachers WHERE email = 'mehnaz.chowdhury@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-4101'), (SELECT id FROM teachers WHERE email = 'anisul.karim@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-4101'), (SELECT id FROM teachers WHERE email = 'farhana.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-4102'), (SELECT id FROM teachers WHERE email = 'farhana.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-4201'), (SELECT id FROM teachers WHERE email = 'sabbir.ahmed@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-4202'), (SELECT id FROM teachers WHERE email = 'nusrat.jahan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CSE-4202'), (SELECT id FROM teachers WHERE email = 'tanvir.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-1101'), (SELECT id FROM teachers WHERE email = 'kamrul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-1201'), (SELECT id FROM teachers WHERE email = 'shahida.akter@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-2101'), (SELECT id FROM teachers WHERE email = 'rashedul.alam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-2101'), (SELECT id FROM teachers WHERE email = 'sadia.noor@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-2102'), (SELECT id FROM teachers WHERE email = 'sadia.noor@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-2201'), (SELECT id FROM teachers WHERE email = 'imran.hossain@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-2202'), (SELECT id FROM teachers WHERE email = 'kamrul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-2202'), (SELECT id FROM teachers WHERE email = 'shahida.akter@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-3101'), (SELECT id FROM teachers WHERE email = 'shahida.akter@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-3102'), (SELECT id FROM teachers WHERE email = 'rashedul.alam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-3201'), (SELECT id FROM teachers WHERE email = 'sadia.noor@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-3201'), (SELECT id FROM teachers WHERE email = 'imran.hossain@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-3202'), (SELECT id FROM teachers WHERE email = 'imran.hossain@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-4101'), (SELECT id FROM teachers WHERE email = 'kamrul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-4102'), (SELECT id FROM teachers WHERE email = 'shahida.akter@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-4102'), (SELECT id FROM teachers WHERE email = 'rashedul.alam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-4201'), (SELECT id FROM teachers WHERE email = 'rashedul.alam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'EEE-4202'), (SELECT id FROM teachers WHERE email = 'sadia.noor@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-1101'), (SELECT id FROM teachers WHERE email = 'golam.mostafa@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-1101'), (SELECT id FROM teachers WHERE email = 'rafiqul.bari@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-1102'), (SELECT id FROM teachers WHERE email = 'rafiqul.bari@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-1201'), (SELECT id FROM teachers WHERE email = 'mahfuza.sultana@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-1202'), (SELECT id FROM teachers WHERE email = 'arif.mahmud@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-1202'), (SELECT id FROM teachers WHERE email = 'golam.mostafa@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-2101'), (SELECT id FROM teachers WHERE email = 'golam.mostafa@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-2102'), (SELECT id FROM teachers WHERE email = 'rafiqul.bari@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-2201'), (SELECT id FROM teachers WHERE email = 'mahfuza.sultana@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-2201'), (SELECT id FROM teachers WHERE email = 'arif.mahmud@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-2202'), (SELECT id FROM teachers WHERE email = 'arif.mahmud@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-3101'), (SELECT id FROM teachers WHERE email = 'golam.mostafa@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-3102'), (SELECT id FROM teachers WHERE email = 'rafiqul.bari@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-3102'), (SELECT id FROM teachers WHERE email = 'mahfuza.sultana@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-3201'), (SELECT id FROM teachers WHERE email = 'mahfuza.sultana@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-3202'), (SELECT id FROM teachers WHERE email = 'arif.mahmud@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-4101'), (SELECT id FROM teachers WHERE email = 'golam.mostafa@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-4101'), (SELECT id FROM teachers WHERE email = 'rafiqul.bari@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'CE-4201'), (SELECT id FROM teachers WHERE email = 'rafiqul.bari@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-1101'), (SELECT id FROM teachers WHERE email = 'nazrul.huq@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-1201'), (SELECT id FROM teachers WHERE email = 'selina.parvin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-1201'), (SELECT id FROM teachers WHERE email = 'zahidul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-2101'), (SELECT id FROM teachers WHERE email = 'zahidul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-2102'), (SELECT id FROM teachers WHERE email = 'rakibul.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-2201'), (SELECT id FROM teachers WHERE email = 'nazrul.huq@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-2201'), (SELECT id FROM teachers WHERE email = 'selina.parvin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-2202'), (SELECT id FROM teachers WHERE email = 'selina.parvin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-3101'), (SELECT id FROM teachers WHERE email = 'zahidul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-3102'), (SELECT id FROM teachers WHERE email = 'rakibul.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-3102'), (SELECT id FROM teachers WHERE email = 'nazrul.huq@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-3201'), (SELECT id FROM teachers WHERE email = 'nazrul.huq@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-3202'), (SELECT id FROM teachers WHERE email = 'selina.parvin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-4101'), (SELECT id FROM teachers WHERE email = 'zahidul.islam@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-4101'), (SELECT id FROM teachers WHERE email = 'rakibul.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-4102'), (SELECT id FROM teachers WHERE email = 'rakibul.hasan@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'MPE-4201'), (SELECT id FROM teachers WHERE email = 'nazrul.huq@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-1101'), (SELECT id FROM teachers WHERE email = 'momtaz.begum@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-1101'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-1201'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-2101'), (SELECT id FROM teachers WHERE email = 'shabnam.ferdous@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-2102'), (SELECT id FROM teachers WHERE email = 'momtaz.begum@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-2102'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-2201'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-3101'), (SELECT id FROM teachers WHERE email = 'shabnam.ferdous@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-3201'), (SELECT id FROM teachers WHERE email = 'momtaz.begum@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-3201'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-3202'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-4101'), (SELECT id FROM teachers WHERE email = 'shabnam.ferdous@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-4102'), (SELECT id FROM teachers WHERE email = 'momtaz.begum@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-4102'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'TE-4201'), (SELECT id FROM teachers WHERE email = 'habibur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1101'), (SELECT id FROM teachers WHERE email = 'aminul.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1102'), (SELECT id FROM teachers WHERE email = 'ruma.das@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1102'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1103'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1104'), (SELECT id FROM teachers WHERE email = 'aminul.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1201'), (SELECT id FROM teachers WHERE email = 'ruma.das@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1201'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1202'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-1203'), (SELECT id FROM teachers WHERE email = 'aminul.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-2101'), (SELECT id FROM teachers WHERE email = 'ruma.das@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-2101'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-2102'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-2201'), (SELECT id FROM teachers WHERE email = 'aminul.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-3101'), (SELECT id FROM teachers WHERE email = 'ruma.das@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-3101'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'A&S-3201'), (SELECT id FROM teachers WHERE email = 'jamil.uddin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-1101'), (SELECT id FROM teachers WHERE email = 'shamima.nasrin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-1102'), (SELECT id FROM teachers WHERE email = 'tahmid.zaman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-1102'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-1201'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-1202'), (SELECT id FROM teachers WHERE email = 'shamima.nasrin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-2101'), (SELECT id FROM teachers WHERE email = 'tahmid.zaman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-2101'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-2102'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-2201'), (SELECT id FROM teachers WHERE email = 'shamima.nasrin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-3101'), (SELECT id FROM teachers WHERE email = 'tahmid.zaman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-3101'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-3201'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-4101'), (SELECT id FROM teachers WHERE email = 'shamima.nasrin@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-4201'), (SELECT id FROM teachers WHERE email = 'tahmid.zaman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'ARCH-4201'), (SELECT id FROM teachers WHERE email = 'farzana.kabir@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-1101'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-1102'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-1201'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-1201'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-1202'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-2101'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-2102'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-2102'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-2201'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-3101'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-3102'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-3102'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-3201'), (SELECT id FROM teachers WHERE email = 'nabila.haque@ums.edu'));
INSERT INTO course_instructors VALUES((SELECT id FROM courses WHERE code = 'SoB-4201'), (SELECT id FROM teachers WHERE email = 'mizanur.rahman@ums.edu'));

