server.port=8100

# Unlike client registration, can't configure name for resource server
# Name must be 'resourceserver', otherwise it won't work
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8000/realms/ums
