server.port=8100

# Unlike client registration, can't configure name for resource server
# Name must be 'resourceserver', otherwise it won't work
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8000/realms/ums

spring.datasource.url=jdbc:postgresql://localhost:5432/ums
spring.datasource.username=postgres
spring.datasource.password=12345

# By default, Spring executes schema.sql & data.sql only in embedded mode
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

ums.upload.dir=/tmp/ums/uploads
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
